SourMesen/Mesen2

Core/Gameboy/Gameboy.cpp
Core/Gameboy/GameboyHeader.h
Core/NES/BaseMapper.cpp
Core/NES/Debugger/NesDebugger.cpp
Core/NES/Loaders/iNesLoader.cpp
Core/NES/Mappers/Bandai/BandaiFcg.h
Core/NES/Mappers/Homebrew/MagicFloor218.h
Core/NES/Mappers/Homebrew/UnRom512.h
Core/NES/Mappers/Nintendo/MMC5.h
Core/NES/RomData.h
Utilities/Serializer.h
makefile

Opening notes:
- I know from the thread's opening post that you said you wouldn't review PRs, but since #1, I'm guessing "fix the build" PRs should be acceptable? Let me know if you'd like the changes submitted another way.
- I tested the final product, and it works correctly!
- Since the Makefile claims it's compatible with GCC, I'm assuming that my GCC—12.21—is stricter than older versions, and that's why the build is failing for me.
- Also, honestly, that's not a bad Makefile. Dare I say, a good one even!
This fixes building on my box with `make -j8 LTO=true USE_GCC=true`. I can provide specific compiler versions etc. if you want.
<details><summary>Fixed compile errors</summary>
```
In file included from Utilities/Serializer.cpp:3:
Utilities/Serializer.h:429:18: error: explicit …
```

Fix build errors with GCC

---

.github/workflows/build.yml

- Coalesce Linux jobs (keeping the GCC on Ubuntu 20 combo disabled, at least for now)
- Update APT database before grabbing packages (otherwise we might get spurious failures, oops!)
- Also disable the .NET "first time experience" which is just annoying here.

Fix up Linux CI

---

.gitignore
Linux/SdlRenderer.h
Linux/SdlSoundManager.h
makefile

The Makefile is currently hardcoding the path to the SDL2 headers, and on ARM Macs this is not where homebrew puts SDL2. This pull request updates it to use `sdl2-config --cflags` instead. The Makefile already called this, but only used it when linking the object together and not when compiling the source files.
Additionally, the headers that include SDL2 included it by `<SDL2/SDL.h>`, while `sdl2-config`'s output assumes `"SDL.h"` instead, so this was updated as well.
Also added build files for Linux and macOS to the .gitignore.

Use sdl2-config for SDL2 includes (fixes compilation on ARM Macs with homebrew SDL2)

---

UI/Program.cs
UI/UI.csproj

Avalonia bug documented at https://github.com/AvaloniaUI/Avalonia/issues/4427.
Changes herein allow this to build on both Gentoo and Arch Linux.
Should you wish to change the default font to a microsoft default, please set an alternate font like Liberation or DejaVu in case a linux user didn't install corefonts.

Linux-related Avalonia/UI bugfix.

---

UI/Debugger/Utilities/DebugShortcutManager.cs
UI/Windows/MainWindow.axaml.cs

This pull request makes some changes to prevent macOS from making an alert sound on every keypress. It does this by setting `Handled` on some key-events to true.
This happens in DebugShortcutManager, when `Click` is called on an action (currently unconditionally), and in the key-handler for the main window, where it happens on any keypress that is not a modifier key and does not have the meta-key (Command) active, here only when running on macOS (not setting on Command is to prevent it blocking Cmd-Q and such).
Note that not setting it on modifier keys is to work around an issue where, when Handled is set, dual-modifier keys drops the event for that third key entirely (e.g. CTRL+ALT+R) (but only when pressed in certain orders, ALT+CTRL+R works fine). This affects the window for setting up …

macOS: Prevent alert sound on keypresses

---

Core/Gameboy/GbDmaController.cpp

It reads a 161st byte which apparently causes the debugger to complain about an uninitialized memory read if you have that enabled and the byte at $XXA0 happens to never have been written to (even though this DMA transfer should apparently only apply for $XX00-$XX9F).
I'm hoping I didn't break anything!

GB: Fixed OAM DMA reading one extra byte

---

UI/Debugger/Integration/WlaDxImporter.cs

This syntax is a bit gnarly, and I am not entirely convinced that the WLA-DX V2 addr-to-line symbol mapping is actually correct in WLA-DX's repo. I agree with the concerns in the code that there are oddities to the Line 0 or Line 1 conversion.
See: https://github.com/vhelin/wla-dx/blob/800c3f8d332f4d1c2846c65e43b919af89de89f1/doc/symbols.rst

Add WLA-DX V2 symbol (.sym) support

---

.github/workflows/build.yml
UI/Mesen.entitlements

Allows the uploaded macos `.app` artifact to be used on other machines. I setup the actions on my fork and tested the downloaded artifact. Note that this is selfsigned, so users will need to bypass gatekeeper to allow this to run. You have to pay $99/yr to get around that restriction...
This change requires creating a self signed certificate, and also requires a few changes to match the data you used when creating the certificate.
This guide explains how to set it up for a Apple Developer Account certificate (which costs $99/yr ...) but you can slightly change he instructions to get a self signed certificate. https://localazy.com/blog/how-to-automatically-sign-macos-apps-using-github-actions
Instead of requesting the certificate from a certificate authority, choose `Create a …

Add macos codesigning

---

Core/SNES/Input/SnesMouse.h

This code approximates a real SNES mouse and has a bool for a non-existent UI option for SNES Mouse Accuracy Mode. It also lets the mouse move 1 pixel despite sensitivity settings in Mesen classic behavior.

Add SNES Accurate Mouse Movement

---

Core/SNES/Input/SnesMouse.h

The SNES Mouse will maintain and report the last direction is was moved in. I don't know if this information was ever used, but it is hardware accurate. Cheers!

SNES Mouse maintains Up and Left flags

---

UI/Debugger/Integration/WlaDxImporter.cs

WLA-DX can generate files with null line mappings. This will happen if your source file does not have any labels directly but does .include other files with labels.
`games/sprites.i`
```
.section "Sprites" bank 3 slot "ROM"
.include "resources/sprites/plane/plane.i"
.ends
```
The generated symbols
```
[source files v2]
0001:0001 3a35f56a game\main.asm 
...
[addr-to-line mapping v2]
...
00018002 03:0002 8002 0001:0000:000018f1
00018005 03:0005 8005 0001:0000:00000000
000198f8 03:18f8 98f8 0001:0000:000018f4
000198f9 03:18f9 98f9 0001:0000:00000001
000198fb 03:18fb 98fb 0001:0000:00000000
```
The specific error here is the `addr-to-line` mapping. It is requesting source file 0, which does not exist. This cause the debugger to error:
The better fix would be to have `WLA-DX` fix their mapping …

WlaDxImporter: Ignore fileId with a mapping of 0

---

UI/UI.csproj

When attempting to build on Ubuntu 22, the publish step was hanging here indefinitely:
```
$ make
mkdir -p bin/linux-x64/Release/Dependencies
rm -fr bin/linux-x64/Release/Dependencies/*
cp InteropDLL/obj.linux-x64/MesenCore.so bin/linux-x64/Release/MesenCore.so
#Called twice because the first call copies native libraries to the bin folder which need to be included in Dependencies.zip
cd UI && dotnet publish -c Release -p:OptimizeUi="true" -r linux-x64 --no-self-contained true -p:PublishSingleFile=true
Microsoft (R) Build Engine version 17.0.1+b177f8fa7 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.
Determining projects to restore...
All projects are up-to-date for restore.
```
Enabling verbose output showed that when trying to perform the command `rm -r Dependencies`, …

Linux build: force delete of Dependencies

---

README.md

As [mentioned previously](https://github.com/SourMesen/Mesen2/pull/24), I've been working on trying to get Mesen working on my Steam Deck. Thanks to the [effort being put in the CI pipeline](https://github.com/SourMesen/Mesen2/pull/25), Mesen works very well with the AppImage nightly builds.
Albeit, there are [some caveats related to Avalonia UI and Gamescope](https://github.com/AvaloniaUI/Avalonia/pull/14366) (with a possible solution [being reverted](https://github.com/AvaloniaUI/Avalonia/pull/14573)) that warrant specific instructions how to use Mesen on the Steam Deck.
Hence why I created this PR to help other users with running Mesen on their Steam Deck.
I added the following to the README.md to aid Steam Deck/SteamOS users (it is hidden in normal view unless the user clicks on the …

docs: add Steam Deck instructions to README

---

.github/workflows/build.yml
README.md

macOS M1 build runners are now available using the `macos-14` tag, so this PR adds that build runner and links them in the README. I don't really mind if you don't want them in the readme yet, but i think they are plenty stable in my experience.

Enable and link macOS builds in the README

---

Core/NES/NesPpu.cpp

If all of those options are on, the extra sprites will be pulled from the bg tile banks instead of the sprite banks.

Fix MMC5 sprite display when using 8x16 mode with 8kb window and reduce sprite flicker enabled

---

UI/Utilities/MouseManager.cs

It looks like setting both the cursor on the software renderer as using the method from the input API causes the cursor to act oddly on macOS, with delayed state changes and sometimes getting the cursor stuck being invisible.
This PR simply makes it not set it on the renderer if running on macOS, which seems to fix these issues.

MacOS: Fix cursor oddness

---

makefile

Passing `OptimizeUI` removes the debug tools, which are referenced by `#if DEBUG` code

Fix building in Debug mode on Linux

---

UI/Program.cs

Set Avalonia's EnableInputFocusProxy flag for gamescope (SteamOS / Steam Deck), which fixes issues with the menus

UI: Fixed input issues for gamescope

---

UI/Debugger/Controls/CodeScrollBar.axaml.cs
UI/Debugger/Controls/HexEditor.cs
UI/Debugger/Utilities/CodeViewerSelectionHandler.cs

The code viewer in the debugger and the memory editor scroll line by line. With the way this was currently implemented, these are quite unresponsive and hard to scroll with a trackpad. This was caused by events with a delta of less than ~0.33 being ignored completely, and slowly scrolling with a trackpad only produces such events.
This MR updates the code to keep track of the fractional values and accumulates them for determining the amount to actually scroll. This greatly improves the experience of scrolling the debugger and memory editor with a trackpad.
A quick check with a notched scroll-wheel mouse seems to give no difference in behaviour (as these only give events of exactly 1 or -1, in which case the changed code should not behave differently).

UI: Keep track of fractional scrolling (debugger/memory editor)

---

MacOS/MacOSGameController.h
MacOS/MacOSGameController.mm
MacOS/MacOSKeyManager.h
MacOS/MacOSKeyManager.mm
UI/UI.csproj
makefile

This PR adds support for controllers to MacOS. The implementation is roughly based on how it works on Linux, with a separate MacOSGameController class.
I marked this as draft for now:
- This makes use of Apple's GCController API, which is a relatively recent API mainly for MFI-gamepads. This likely means it does not have compatibility with gamepads that are not explicitly supported by Apple.
- This is also a recent API as in, that with the API's now used, the minimum MacOS version is bumped to at least 11.0 Big Sur, which might be too recent.
- I am unable to get the current master to run on macOS at all, it compiles fine but gives an error that it can't find 'Avalonia.Vullan' when trying to run with `make run`.
I'm not sure what happened, but I did notice that my branch for the …

MacOS: Add controller support
